[package]
name = "sgp4"
version = "0.1.0"
authors = ["Alexandre Marcireau <alexandre.marcireau@gmail.com>"]
edition = "2018"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"
toml = "0.5"

[[bench]]
name = "propagate"
harness = false
